package com.toyota.tmna.lexusdrivers.core.util;

public class GlobalNavConstants {

	public static final String KEY_DATA = "data";
	public static final String KEY_NAVIGATION_LINK = "NavigationLinks";
	public static final String KEY_SELECTED_VEHICLE = "SelectVehicle";
	public static final String KEY_LOGGED_IN = "LoggedIn";
	public static final String KEY_HEADER_LOGO = "HeaderLogo";
	public static final String KEY_LOGGED_OUT = "LoggedOut";
	public static final String KEY_WELCOME_EXPERIENCE = "WelcomeExperience";
	public static final String KEY_NAV_SEARCH = "LdNavSearch";
	public static final String KEY_FUEL_GRADES = "FuelGrades";
	public static final String KEY_MY_FILTER = "MYCOFilter";
	public static final String KEY_FSPORT_FILTER = "FsportFilter";
	public static final String KEY_LEGACY_MODEL_EXPERIENCE = "LegacyModelFilter"; 
	public static final String KEY_NAME = "name";
	public static final String KEY_OBJ = "obj";
	public static final String KEY_VALUE = "value";
	public static final String KEY_LABEL = "label";
	public static final String KEY_NAV_LABEL = "navLabel";
	public static final String KEY_NAVLINK = "navLink";
	public static final String KEY_NAV_ICON = "navIcon";
	public static final String KEY_CHILDREN = "children";
	public static final String KEY_BODY = "body";
	public static final String KEY_TITLE = "title";
	public static final String KEY_TEXT = "text";
	public static final String KEY_DESCRIPTION = "description";
	public static final String KEY_HREF = "href";
	public static final String KEY_URL = "url";
	public static final String KEY_ANCHOR = "anchor";
	public static final String KEY_TARGET = "target";
	public static final String KEY_LINKTYPE = "linktype";
	public static final String KEY_STYLECLASS = "styleClass";
	public static final String KEY_BUTTON_LABEL = "buttonLabel";
	public static final String KEY_SUCCESS_URL = "successPageUrl";
	public static final String KEY_GARAGE_TEXT = "manageGarageText";
	public static final String KEY_GARAGE_LINK = "manageGarageLink";
	public static final String KEY_CAR_IMAGE = "carImage";
	public static final String KEY_CAR_MODEL = "carModel";
	public static final String KEY_FIND_DEALER_LABEL = "findDealerLabel";
	public static final String KEY_FIND_DEALER_LINK = "findDealerLink";
	public static final String KEY_VEHICLE_DEFAULT_TEXT = "vehicleSelectorDefaultText";
	public static final String KEY_VIN_LABEL = "vINLabel";
	public static final String KEY_YEAR_DEFAULT_TEXT = "yearSelectorDefaultText";
	public static final String KEY_BOTTOM_TEXT = "bottomText";
	public static final String KEY_IMAGE = "image";
	public static final String KEY_CLASS = "class";
	public static final String KEY_ENABLE_EXPERIENCE = "enableExperience";
	public static final String KEY_DEVICE_STYLES = "deviceStyles";
	public static final String KEY_CAROUSEL_THUMBNAIL = "thumbnail";
	public static final String KEY_VIDEO_SLIDE="videoSlide";
	public static final String KEY_SRC="src";
	public static final String KEY_LINKOUT_URL="linkoutUrl";
	
	public static final String PROP_SECTION_LABEL = "sectionLabel";
	public static final String PROP_ERROR_MSG_NAME = "errMsgName";
	public static final String PROP_ERROR_MSG_TITLE = "errMsgTitle";
	public static final String PROP_ERROR_MSG_BODY = "errMsgBody";
	public static final String PROP_GARAGE_NAME = "manageGarageName";
	public static final String PROP_GARAGE_LINK = "manageGarageLink";
	public static final String PROP_GARAGE_LINK_TYPE = "manageGarageLinkType";
	public static final String PROP_GARAGE_VALUE = "manageGarageValue";
	public static final String PROP_GARAGE_TEXT = "manageGarageText";
	public static final String PROP_GARAGE_TITLE = "garageTitle";
	public static final String PROP_GARAGE_DESCRIPTION = "garageDescription";
	public static final String PROP_DEALER_LABEL = "findDealerLabel";
	public static final String PROP_DEALER_LINK = "findDealerLink";
	public static final String PROP_NAME = "name";
	public static final String PROP_LABEL = "label";
	public static final String PROP_NAV_LABEL_LEVEL_TWO = "navLabel";
	public static final String PROP_NAV_LABEL_LEVEL_ONE = "navlabel";
	public static final String PROP_URL = "url";
	public static final String PROP_ANCHOR = "anchor";
	public static final String PROP_TARGET = "target";
	public static final String PROP_LINK_TYPE_LEVEL_TWO = "linktype";
	public static final String PROP_LINK_TYPE_LEVEL_ONE = "linkType";
	public static final String PROP_STYLECLASS = "styleClass";
	public static final String PROP_QUICKNAV_LABEL = "quicknavLabel";
	public static final String PROP_QUICK_LABEL = "quickLabel";
	public static final String PROP_NAV_LINK = "navLink";
	public static final String PROP_NAV_ICON = "navIcon";
	public static final String PROP_QUICK_LINK_URL = "quicklinkURL";
	public static final String PROP_QUICK_LINK_TYPE = "quicklinkURLType";
	public static final String PROP_SELECT_CAROUSEL_TITLE = "selectcarouselTitle";
	public static final String PROP_CAROUSEL_THUMBNAIL ="carouselThumbnail";
	public static final String PROP_VIDEO_SLIDE="videoslide";
	public static final String PROP_LINKOUT_URL="carousellinkoutUrl";
	public static final String PROP_SECTION_DESCRIPTION = "sectionDescription";
	public static final String PROP_VEHICLE_SELECT_TEXT = "vehicleSelectText";
	public static final String PROP_VIN_LABEL = "vINLabel";
	public static final String PROP_VEHICLE_YEAR_SELECTOR = "vehicleYearSelector";
	public static final String PROP_BUTTON_LABEL = "buttonLabel";
	public static final String PROP_SUCCESS_URL = "successPageUrl";
	public static final String PROP_BOTTOM_TEXT = "bottomText";
	public static final String PROP_BENIFITS_TITLE = "benefitsTitle";
	public static final String PROP_BODY = "body";
	public static final String PROP_CTA_LABEL = "ctaLabel";
	public static final String PROP_CTA_LINK = "ctaLink";
	public static final String PROP_CTA_TYPE = "ctaType";
	public static final String PROP_LINK_LABLE = "linkLabel";
	public static final String PROP_LINK_URL = "linkUrl";
	public static final String PROP_DEVICE_STYLE = "deviceStyles";	
	public static final String PROP_NAV_SEARCH = "ld-nav-search";
	public static final String PROP_FUEL_GRADES = "fuel-grades";
	public static final String PROP_MY_FILTER = "my-filter";
	public static final String PROP_FSPORT_FILTER = "fsport-filter";
	public static final String PROP_LEGACY_MODEL_EXPERIENCE = "legacy-model-filter";
	public static final String PROP_ENABLE_EXPERIENCE = "enableExperience";
	public static final String PROP_DEVICE_STYLES = "deviceStyles";
	
	
	
	public static final String NODE_NAVIGATION_MESSAGE = "navigationMessages";
	public static final String NODE_MANAGE_GARAGE = "manageGarage";
	public static final String NODE_NAVIGATION_LINKS = "navigationLinks";
	public static final String NODE_CAROUSEL_TILES = "tiles";
	public static final String NODE_CHILDREN = "children";
	public static final String NODE_QUICK_LINKS = "quicklinks";
	public static final String NODE_LOGGED_OUT = "loggedOut";
	public static final String NODE_LOGGED_IN = "loggedIn";
	
	public static final String HTML_ELE_LINK = "<link ";
	public static final String HTML_START_ATTR = "='";
	public static final String HTML_END_ATTR = "'";
	public static final String HTML_ELE_END = "/>";
	public static final String HTML_ELE_IMG = "<image ";
	public static final String HTML_ATTR_SRC = "src='";
	public static final String HTML_ATTR_ALT = "alt='";
	
	public static final String CONTENT_FRAGMENT_APP_CONFIG = "/content/dam/lexusdrivers/content-fragments/appconfig/app-config/jcr:content/data/master";
}
